# Generated by Django 2.0.2 on 2018-11-29 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('act', models.IntegerField(default=0, null=True)),
                ('scene', models.IntegerField(default=0, null=True)),
                ('pdfPath', models.CharField(max_length=200, null=True)),
                ('answers', models.CharField(max_length=500, null=True)),
                ('winPun', models.CharField(max_length=300, null=True)),
                ('losePun', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'Puzzles',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authClone', models.ForeignKey(db_column='scorer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Scores',
            },
        ),
    ]
