# Generated by Django 2.1.5 on 2019-02-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzles',
            old_name='answers',
            new_name='answer',
        ),
    ]
