# Generated by Django 2.1.5 on 2019-02-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0002_auto_20190209_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzles',
            name='hint1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='puzzles',
            name='hint2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='puzzles',
            name='hint3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
