# Generated by Django 2.1.5 on 2019-02-09 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0003_auto_20190209_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedGuesses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guess', models.CharField(max_length=200, null=True)),
                ('correct', models.BooleanField(null=True)),
                ('submitTime', models.DateTimeField(null=True)),
                ('puzzle', models.ForeignKey(db_column='puzzle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PHapp.Puzzles')),
            ],
            options={
                'db_table': 'SubmittedGuesses',
            },
        ),
        migrations.AlterField(
            model_name='teams',
            name='authClone',
            field=models.ForeignKey(db_column='authClone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='teams',
            table='Teams',
        ),
        migrations.AddField(
            model_name='submittedguesses',
            name='team',
            field=models.ForeignKey(db_column='team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PHapp.Teams'),
        ),
    ]
