# Generated by Django 2.1.5 on 2019-02-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0005_teams_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzles',
            name='released',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
