# Generated by Django 2.1.5 on 2019-02-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0006_puzzles_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzles',
            old_name='released',
            new_name='releaseStatus',
        ),
    ]
