# Generated by Django 2.1.5 on 2019-02-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0008_auto_20190209_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('aussie', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'Individuals',
            },
        ),
        migrations.AddField(
            model_name='teams',
            name='teamEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='member1',
            field=models.ForeignKey(db_column='member1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member1', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member10',
            field=models.ForeignKey(db_column='member10', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member10', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member2',
            field=models.ForeignKey(db_column='member2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member2', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member3',
            field=models.ForeignKey(db_column='member3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member3', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member4',
            field=models.ForeignKey(db_column='member4', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member4', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member5',
            field=models.ForeignKey(db_column='member5', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member5', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member6',
            field=models.ForeignKey(db_column='member6', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member6', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member7',
            field=models.ForeignKey(db_column='member7', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member7', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member8',
            field=models.ForeignKey(db_column='member8', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member8', to='PHapp.Individuals'),
        ),
        migrations.AddField(
            model_name='teams',
            name='member9',
            field=models.ForeignKey(db_column='member9', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member9', to='PHapp.Individuals'),
        ),
    ]
