# Generated by Django 2.1.7 on 2019-02-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0009_auto_20190214_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuals',
            name='melb',
            field=models.BooleanField(null=True),
        ),
    ]
