# Generated by Django 2.1.7 on 2019-02-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0010_individuals_melb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='aussie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='melb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submittedguesses',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
