# Generated by Django 2.1.7 on 2019-02-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0011_auto_20190217_1216'),
        ('PHapp', '0010_auto_20190214_1848'),
    ]

    operations = [
    ]
