# Generated by Django 2.1.7 on 2019-02-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0012_merge_20190218_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member10',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member4',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member5',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member6',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member7',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member8',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member9',
        ),
        migrations.AddField(
            model_name='individuals',
            name='team',
            field=models.ForeignKey(db_column='authClone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PHapp.Teams'),
        ),
    ]
