# Generated by Django 2.1.7 on 2019-02-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0013_auto_20190218_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='team',
            field=models.ForeignKey(db_column='team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PHapp.Teams'),
        ),
    ]
