# Generated by Django 2.0.2 on 2019-02-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0014_auto_20190218_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='teamEmail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamName',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
