# Generated by Django 2.0.2 on 2019-02-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0015_auto_20190219_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='teamEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
