# Generated by Django 2.1.7 on 2019-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0016_auto_20190219_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='aussie',
            field=models.BooleanField(default=False),
        ),
    ]
