# Generated by Django 2.1.7 on 2019-02-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0017_teams_aussie'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='avHr',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='avMin',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='avSec',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
