# Generated by Django 2.1.7 on 2019-02-20 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0018_auto_20190220_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedguesses',
            name='team',
            field=models.ForeignKey(db_column='team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PHapp.Teams'),
        ),
    ]
