# Generated by Django 2.1.7 on 2019-02-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0020_correctguesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctguesses',
            name='submitTime',
        ),
    ]
