# Generated by Django 2.1.7 on 2019-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0022_auto_20190220_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='avHr',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='avMin',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='avSec',
        ),
        migrations.AddField(
            model_name='teams',
            name='avSolve',
            field=models.TimeField(null=True),
        ),
    ]
