# Generated by Django 2.0.2 on 2019-06-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0027_altanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubelets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cubeletId', models.IntegerField(null=True)),
                ('cubeface', models.IntegerField(null=True)),
                ('colour', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'Cubelets',
            },
        ),
        migrations.AddField(
            model_name='puzzles',
            name='cubelet1',
            field=models.ForeignKey(db_column='Cubelets1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cubelet1', to='PHapp.Cubelets'),
        ),
        migrations.AddField(
            model_name='puzzles',
            name='cubelet2',
            field=models.ForeignKey(db_column='Cubelets2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cubelet2', to='PHapp.Cubelets'),
        ),
        migrations.AddField(
            model_name='puzzles',
            name='cubelet3',
            field=models.ForeignKey(db_column='Cubelets3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cubelet3', to='PHapp.Cubelets'),
        ),
        migrations.AddField(
            model_name='puzzles',
            name='cubelet4',
            field=models.ForeignKey(db_column='Cubelets4', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cubelet4', to='PHapp.Cubelets'),
        ),
        migrations.AddField(
            model_name='puzzles',
            name='cubelet5',
            field=models.ForeignKey(db_column='Cubelets5', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cubelet5', to='PHapp.Cubelets'),
        ),
    ]
