# Generated by Django 2.1.7 on 2019-06-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0030_auto_20190623_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzles',
            name='cubelet2',
        ),
        migrations.RemoveField(
            model_name='puzzles',
            name='cubelet3',
        ),
        migrations.RemoveField(
            model_name='puzzles',
            name='cubelet4',
        ),
        migrations.RemoveField(
            model_name='puzzles',
            name='cubelet5',
        ),
    ]
