# Generated by Django 2.0.2 on 2019-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0032_auto_20190801_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msgTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('msg', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Announcements',
            },
        ),
    ]
