# Generated by Django 2.0.2 on 2019-08-05 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PHapp', '0033_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetTokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('altAnswer', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ResetTokens',
            },
        ),
    ]
