# Generated by Django 2.0.2 on 2019-08-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0034_resettokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resettokens',
            old_name='altAnswer',
            new_name='token',
        ),
    ]
