# Generated by Django 2.1.7 on 2019-08-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0035_auto_20190805_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PHapp.Puzzles')),
            ],
        ),
    ]
