# Generated by Django 2.0.2 on 2019-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0037_cubedataaccessrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzles',
            name='hint1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='puzzles',
            name='hint2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='puzzles',
            name='hint3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
