# Generated by Django 2.1.5 on 2019-08-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0039_announcements_erratum'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='solvedMeta1',
            field=models.BooleanField(default=False),
        ),
    ]
