# Generated by Django 2.1.5 on 2019-08-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0040_teams_solvedmeta1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='solvedMeta1',
            new_name='solvedMetaOne',
        ),
    ]
