# Generated by Django 2.1.5 on 2019-08-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0041_auto_20190812_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='solvedMetaTwo',
            field=models.BooleanField(default=False),
        ),
    ]
