# Generated by Django 2.1.5 on 2019-08-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0042_teams_solvedmetatwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzles',
            name='hint1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='puzzles',
            name='hint2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='puzzles',
            name='hint3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
