# Generated by Django 2.1.7 on 2019-08-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0043_auto_20190815_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='msgTime',
            field=models.DateTimeField(null=True),
        ),
    ]
