# Generated by Django 2.1.7 on 2019-08-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0044_auto_20190816_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='msg',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
