# Generated by Django 2.0.2 on 2019-08-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHapp', '0045_auto_20190816_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzles',
            name='credits',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
